spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsweb
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

#Phoenix
app:
  jwt-secret: 03a8f0dd8edb33781a836ac497800b5f9c5c47c2ddbfd0f89581140589725a85
  jwt-expiration-milliseconds: 172800000